In [3]:
import pandas as pd 
df=pd.read_csv("new1.csv")
df

,Date,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
0,1,1,2021,0,5,408.8,442.42,160.61,12.95,2.77,43.19,462
1,2,1,2021,0,6,404.04,561.95,52.85,5.18,2.6,16.43,482
2,3,1,2021,1,7,225.07,239.04,170.95,10.93,1.4,44.29,263
3,4,1,2021,0,1,89.55,132.08,153.98,10.42,1.01,49.19,207
4,5,1,2021,0,2,54.06,55.54,122.66,9.70,0.64,48.88,149
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,27,12,2024,0,5,58.43,249.17,41.69,65.89,0.99,36.25,263
1457,28,12,2024,0,6,33.83,150.77,33.31,66.14,0.79,35.19,113
1458,29,12,2024,1,7,31.21,139.75,27.01,65.94,0.57,35.88,142
1459,30,12,2024,0,1,38.01,152.83,29.12,65.16,0.55,38.38,116
1460,31,12,2024,0,2,80.42,318.96,40.37,64.98,0.84,39.93,209

### Getting the data from the Url

In [ ]:
import pandas as pd

url = "https://gist.githubusercontent.com/kalinchernev/486393efcca01623b18d/raw/countries.csv"  # raw URL

# Read data from URL
df = pd.read_csv(url, on_bad_lines='skip')

# Save to CSV
df.to_csv("data.csv", index=False)

print("Data saved successfully")

In [10]:
pd.read_csv("New1.csv",sep="/r")

C:\Users\saima\AppData\Local\Temp\ipykernel_14664\1052530036.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd.read_csv("New1.csv",sep="/r")

     Date,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
0     1,1,2021,0,5,408.8,442.42,160.61,12.95,2.77,43...
1     2,1,2021,0,6,404.04,561.95,52.85,5.18,2.6,16.4...
2     3,1,2021,1,7,225.07,239.04,170.95,10.93,1.4,44...
3     4,1,2021,0,1,89.55,132.08,153.98,10.42,1.01,49...
4     5,1,2021,0,2,54.06,55.54,122.66,9.7,0.64,48.88...
...                                                 ...
1456  27,12,2024,0,5,58.43,249.17,41.69,65.89,0.99,3...
1457  28,12,2024,0,6,33.83,150.77,33.31,66.14,0.79,3...
1458  29,12,2024,1,7,31.21,139.75,27.01,65.94,0.57,3...
1459  30,12,2024,0,1,38.01,152.83,29.12,65.16,0.55,3...
1460  31,12,2024,0,2,80.42,318.96,40.37,64.98,0.84,3...

[1461 rows x 1 columns]

### for getting the data separate

In [21]:
pd.read_csv("New3.tsv",sep="/t")

C:\Users\saima\AppData\Local\Temp\ipykernel_14664\593493624.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd.read_csv("New3.tsv",sep="/t")

     Days,Year
0       5,2021
1       6,2021
2       7,2021
3       1,2021
4       2,2021
...        ...
1456    5,2024
1457    6,2024
1458    7,2024
1459    1,2024
1460    2,2024

[1461 rows x 1 columns]

In [22]:
df

,Date,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
0,1,1,2021,0,5,408.8,442.42,160.61,12.95,2.77,43.19,462
1,2,1,2021,0,6,404.04,561.95,52.85,5.18,2.6,16.43,482
2,3,1,2021,1,7,225.07,239.04,170.95,10.93,1.4,44.29,263
3,4,1,2021,0,1,89.55,132.08,153.98,10.42,1.01,49.19,207
4,5,1,2021,0,2,54.06,55.54,122.66,9.70,0.64,48.88,149
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,27,12,2024,0,5,58.43,249.17,41.69,65.89,0.99,36.25,263
1457,28,12,2024,0,6,33.83,150.77,33.31,66.14,0.79,35.19,113
1458,29,12,2024,1,7,31.21,139.75,27.01,65.94,0.57,35.88,142
1459,30,12,2024,0,1,38.01,152.83,29.12,65.16,0.55,38.38,116
1460,31,12,2024,0,2,80.42,318.96,40.37,64.98,0.84,39.93,209

### for changing the column

In [24]:
pd.read_csv("New1.csv",header=1)

       1  1.1  2021  0  5   408.8  442.42  160.61  12.95  2.77  43.19  462
0      2    1  2021  0  6  404.04  561.95   52.85   5.18   2.6  16.43  482
1      3    1  2021  1  7  225.07  239.04  170.95  10.93   1.4  44.29  263
2      4    1  2021  0  1   89.55  132.08  153.98  10.42  1.01  49.19  207
3      5    1  2021  0  2   54.06   55.54  122.66   9.70  0.64  48.88  149
4      6    1  2021  0  3  155.59  180.14  142.71  10.29  1.18  44.47  252
...   ..  ...   ... .. ..     ...     ...     ...    ...   ...    ...  ...
1455  27   12  2024  0  5   58.43  249.17   41.69  65.89  0.99  36.25  263
1456  28   12  2024  0  6   33.83  150.77   33.31  66.14  0.79  35.19  113
1457  29   12  2024  1  7   31.21  139.75   27.01  65.94  0.57  35.88  142
1458  30   12  2024  0  1   38.01  152.83   29.12  65.16  0.55  38.38  116
1459  31   12  2024  0  2   80.42  318.96   40.37  64.98  0.84  39.93  209

[1460 rows x 12 columns]

### if the name of the column not given then

In [26]:
pd.read_csv("New3.tsv",names=["din","saal"])

       din  saal
0     Days  Year
1        5  2021
2        6  2021
3        7  2021
4        1  2021
...    ...   ...
1457     5  2024
1458     6  2024
1459     7  2024
1460     1  2024
1461     2  2024

[1462 rows x 2 columns]

### for changing the index colm

In [27]:
pd.read_csv("New1.csv",index_col="Date")

,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
Date,,,,,,,,,,,
1,1,2021,0,5,408.8,442.42,160.61,12.95,2.77,43.19,462
2,1,2021,0,6,404.04,561.95,52.85,5.18,2.6,16.43,482
3,1,2021,1,7,225.07,239.04,170.95,10.93,1.4,44.29,263
4,1,2021,0,1,89.55,132.08,153.98,10.42,1.01,49.19,207
5,1,2021,0,2,54.06,55.54,122.66,9.70,0.64,48.88,149
...,...,...,...,...,...,...,...,...,...,...,...
27,12,2024,0,5,58.43,249.17,41.69,65.89,0.99,36.25,263
28,12,2024,0,6,33.83,150.77,33.31,66.14,0.79,35.19,113
29,12,2024,1,7,31.21,139.75,27.01,65.94,0.57,35.88,142
30,12,2024,0,1,38.01,152.83,29.12,65.16,0.55,38.38,116
31,12,2024,0,2,80.42,318.96,40.37,64.98,0.84,39.93,209

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1461 non-null   int64
 1   Month           1461 non-null   int64
 2   Year            1461 non-null   int64
 3   Holidays_Count  1461 non-null   int64
 4   Days            1461 non-null   int64
 5   PM2.5           1461 non-null   object
 6   PM10            1461 non-null   object
 7   NO2             1461 non-null   float64
 8   SO2             1461 non-null   float64
 9   CO              1461 non-null   object
 10  Ozone           1461 non-null   float64
 11  AQI             1461 non-null   int64
dtypes: float64(3), int64(6), object(3)
memory usage: 137.1+ KB

In [34]:
import numpy as np
df=pd.read_csv("New1.csv",dtype={'Days':np.float64})
df

,Date,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
0,1,1,2021,0,5.0,408.8,442.42,160.61,12.95,2.77,43.19,462
1,2,1,2021,0,6.0,404.04,561.95,52.85,5.18,2.6,16.43,482
2,3,1,2021,1,7.0,225.07,239.04,170.95,10.93,1.4,44.29,263
3,4,1,2021,0,1.0,89.55,132.08,153.98,10.42,1.01,49.19,207
4,5,1,2021,0,2.0,54.06,55.54,122.66,9.70,0.64,48.88,149
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,27,12,2024,0,5.0,58.43,249.17,41.69,65.89,0.99,36.25,263
1457,28,12,2024,0,6.0,33.83,150.77,33.31,66.14,0.79,35.19,113
1458,29,12,2024,1,7.0,31.21,139.75,27.01,65.94,0.57,35.88,142
1459,30,12,2024,0,1.0,38.01,152.83,29.12,65.16,0.55,38.38,116
1460,31,12,2024,0,2.0,80.42,318.96,40.37,64.98,0.84,39.93,209

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1461 non-null   int64
 1   Month           1461 non-null   int64
 2   Year            1461 non-null   int64
 3   Holidays_Count  1461 non-null   int64
 4   Days            1461 non-null   float64
 5   PM2.5           1461 non-null   object
 6   PM10            1461 non-null   object
 7   NO2             1461 non-null   float64
 8   SO2             1461 non-null   float64
 9   CO              1461 non-null   object
 10  Ozone           1461 non-null   float64
 11  AQI             1461 non-null   int64
dtypes: float64(4), int64(5), object(3)
memory usage: 137.1+ KB

### for skiping rows

In [38]:
import numpy as np
df=pd.read_csv("New1.csv",skiprows=lambda x: x % 2==0)
df

      1  1.1  2021  0  5   408.8  442.42  160.61  12.95  2.77  43.19  462
0     3    1  2021  1  7  225.07  239.04  170.95  10.93  1.40  44.29  263
1     5    1  2021  0  2   54.06   55.54  122.66   9.70  0.64  48.88  149
2     7    1  2021  0  4  118.39  131.18   98.87   9.81  0.73  48.60  288
3     9    1  2021  0  6  144.01  192.43  108.43  10.41  0.85  42.23  326
4    11    1  2021  0  1  135.92  208.99  105.07  10.49  0.75  55.06  281
..   ..  ...   ... .. ..     ...     ...     ...    ...   ...    ...  ...
725  23   12  2024  0  1  136.27  506.57   63.35  62.14  2.27  30.70  418
726  25   12  2024  1  3   86.53  344.46   52.68  62.88  1.34  29.75  309
727  27   12  2024  0  5   58.43  249.17   41.69  65.89  0.99  36.25  263
728  29   12  2024  1  7   31.21  139.75   27.01  65.94  0.57  35.88  142
729  31   12  2024  0  2   80.42  318.96   40.37  64.98  0.84  39.93  209

[730 rows x 12 columns]

### for getting required rows

In [39]:
import numpy as np
df=pd.read_csv("New1.csv",skiprows=lambda x: x % 2==0,nrows=200)
df

      1  1.1  2021  0  5   408.8  442.42  160.61  12.95  2.77  43.19  462
0     3    1  2021  1  7  225.07  239.04  170.95  10.93  1.40  44.29  263
1     5    1  2021  0  2   54.06   55.54  122.66   9.70  0.64  48.88  149
2     7    1  2021  0  4  118.39  131.18   98.87   9.81  0.73  48.60  288
3     9    1  2021  0  6  144.01  192.43  108.43  10.41  0.85  42.23  326
4    11    1  2021  0  1  135.92  208.99  105.07  10.49  0.75  55.06  281
..   ..  ...   ... .. ..     ...     ...     ...    ...   ...    ...  ...
195  28    1  2022  0  5  107.08  159.79    9.54   8.01  1.35  32.61  224
196  30    1  2022  1  7  136.49  191.22    9.99   8.69  1.38  35.91  270
197   1    2  2022  0  2   200.2  245.48    7.96  11.07  1.48  20.03  376
198   3    2  2022  0  4   122.9  145.08    6.34  12.69  0.55  27.83  302
199   5    2  2022  0  6   106.6  214.40   22.33  11.45  0.81  25.75  196

[200 rows x 12 columns]

### By default we ge the date as string so changing data type we perfrom the parse date

In [43]:
import numpy as np
df=pd.read_csv("New1.csv",parse_dates=['Year'])
df

,Date,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
0,1,1,2021-01-01,0,5,408.8,442.42,160.61,12.95,2.77,43.19,462
1,2,1,2021-01-01,0,6,404.04,561.95,52.85,5.18,2.6,16.43,482
2,3,1,2021-01-01,1,7,225.07,239.04,170.95,10.93,1.4,44.29,263
3,4,1,2021-01-01,0,1,89.55,132.08,153.98,10.42,1.01,49.19,207
4,5,1,2021-01-01,0,2,54.06,55.54,122.66,9.70,0.64,48.88,149
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,27,12,2024-01-01,0,5,58.43,249.17,41.69,65.89,0.99,36.25,263
1457,28,12,2024-01-01,0,6,33.83,150.77,33.31,66.14,0.79,35.19,113
1458,29,12,2024-01-01,1,7,31.21,139.75,27.01,65.94,0.57,35.88,142
1459,30,12,2024-01-01,0,1,38.01,152.83,29.12,65.16,0.55,38.38,116
1460,31,12,2024-01-01,0,2,80.42,318.96,40.37,64.98,0.84,39.93,209

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1461 non-null   int64
 1   Month           1461 non-null   int64
 2   Year            1461 non-null   datetime64[ns]
 3   Holidays_Count  1461 non-null   int64
 4   Days            1461 non-null   int64
 5   PM2.5           1461 non-null   object
 6   PM10            1461 non-null   object
 7   NO2             1461 non-null   float64
 8   SO2             1461 non-null   float64
 9   CO              1461 non-null   object
 10  Ozone           1461 non-null   float64
 11  AQI             1461 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(5), object(3)
memory usage: 137.1+ KB

### for making some thing nan

In [49]:
import numpy as np
df=pd.read_csv("New1.csv",na_values=['Year'])
df

,Date,Month,Year,Holidays_Count,Days,PM2.5,PM10,NO2,SO2,CO,Ozone,AQI
0,1,1,2021,0,5,408.8,442.42,160.61,12.95,2.77,43.19,462
1,2,1,2021,0,6,404.04,561.95,52.85,5.18,2.6,16.43,482
2,3,1,2021,1,7,225.07,239.04,170.95,10.93,1.4,44.29,263
3,4,1,2021,0,1,89.55,132.08,153.98,10.42,1.01,49.19,207
4,5,1,2021,0,2,54.06,55.54,122.66,9.70,0.64,48.88,149
...,...,...,...,...,...,...,...,...,...,...,...,...
1456,27,12,2024,0,5,58.43,249.17,41.69,65.89,0.99,36.25,263
1457,28,12,2024,0,6,33.83,150.77,33.31,66.14,0.79,35.19,113
1458,29,12,2024,1,7,31.21,139.75,27.01,65.94,0.57,35.88,142
1459,30,12,2024,0,1,38.01,152.83,29.12,65.16,0.55,38.38,116
1460,31,12,2024,0,2,80.42,318.96,40.37,64.98,0.84,39.93,209

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1461 non-null   int64
 1   Month           1461 non-null   int64
 2   Year            1461 non-null   int64
 3   Holidays_Count  1461 non-null   int64
 4   Days            1461 non-null   int64
 5   PM2.5           1461 non-null   object
 6   PM10            1461 non-null   object
 7   NO2             1461 non-null   float64
 8   SO2             1461 non-null   float64
 9   CO              1461 non-null   object
 10  Ozone           1461 non-null   float64
 11  AQI             1461 non-null   int64
dtypes: float64(3), int64(6), object(3)
memory usage: 137.1+ KB

### for converting the values

In [61]:
def rename(name):
    try:
        if int(name) == 2024:
            return 'leap'
        else:
            return name
    except:
        return name  # in case of empty or invalid data

df = pd.read_csv("New1.csv", converters={'Year': rename})
print(df)

      Date  Month  Year  Holidays_Count  Days   PM2.5    PM10     NO2    SO2  \
0        1      1  2021               0     5   408.8  442.42  160.61  12.95
1        2      1  2021               0     6  404.04  561.95   52.85   5.18
2        3      1  2021               1     7  225.07  239.04  170.95  10.93
3        4      1  2021               0     1   89.55  132.08  153.98  10.42
4        5      1  2021               0     2   54.06   55.54  122.66   9.70
...    ...    ...   ...             ...   ...     ...     ...     ...    ...
1456    27     12  leap               0     5   58.43  249.17   41.69  65.89
1457    28     12  leap               0     6   33.83  150.77   33.31  66.14
1458    29     12  leap               1     7   31.21  139.75   27.01  65.94
1459    30     12  leap               0     1   38.01  152.83   29.12  65.16
1460    31     12  leap               0     2   80.42  318.96   40.37  64.98

        CO  Ozone  AQI
0     2.77  43.19  462
1      2.6  16.43  482
2      1.4  44.29  263
3     1.01  49.19  207
4     0.64  48.88  149
...    ...    ...  ...
1456  0.99  36.25  263
1457  0.79  35.19  113
1458  0.57  35.88  142
1459  0.55  38.38  116
1460  0.84  39.93  209

[1461 rows x 12 columns]

## Reading from json

In [3]:
import pandas as pd 
df=pd.read_json("test.json")
df

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

### to take data from url

In [ ]:
df = pd.read_json("https://example.com/data.json")

### for changing the type

In [14]:
import numpy as np 
df=pd.read_json("test.json",dtype={'id':np.float64})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9944 entries, 0 to 9943
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9944 non-null   float64
 1   ingredients  9944 non-null   object
dtypes: float64(1), object(1)
memory usage: 155.5+ KB

### for converting dates

In [15]:
df=pd.read_json("test.json",convert_dates=True)